version: 0.2
phases:
  install:
    commands:
        - echo Installing source NPM dependencies...
        - npm install
  pre_build:
    commands:
        - echo Generate environment variables...
        - touch .env.production
        - echo REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID} >> .env.production
        - echo REACT_APP_JOTTER_API_URL=${REACT_APP_JOTTER_API_URL} >> .env.production
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
      - '**/*'
  base-directory: build
  discard-paths: no