version: 0.2
env:
    variables:
        S3_BUCKET: "app.thejotter.xyz"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run build
artifacts:
    files:
        - '**/*'
    base-directory: 'build*'
    discard-paths: yes